# Generated by Django 4.0.5 on 2022-06-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('edad', models.IntegerField(max_length=3)),
                ('titulos',models.IntegerField()),
                ('equipo',models.CharField(max_length=40))
            ],
        ),
    ]
