# Generated by Django 4.0.5 on 2022-06-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
