# Generated by Django 4.0.5 on 2022-06-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVega', '0003_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=20)),
                ('cabeza_de_serie', models.BooleanField()),
            ],
        ),
    ]
