# Generated by Django 4.0.5 on 2022-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVega', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=models.TextField(max_length=500),
        ),
    ]
