# Generated by Django 4.0.5 on 2022-07-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVega', '0006_alter_blog_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=models.CharField(max_length=500),
        ),
    ]
